-- ============================================================================
-- PROJECT: AI-powered Viva Exam System (AIVES)
-- TARGET: PostgreSQL 14+
-- NOTE: Primary keys and UUIDs are generated at the application/logic layer
-- ============================================================================

-- ============================================================================
-- ENUM TYPES
-- ============================================================================

CREATE TYPE bloom_level AS ENUM (
    'REMEMBER',
    'UNDERSTAND',
    'APPLY',
    'ANALYZE'
);

CREATE TYPE question_status AS ENUM (
    'DRAFT_AI',     -- Generated by AI via RAG, awaiting review
    'APPROVED',     -- Approved by lecturer into official bank
    'REJECTED'      -- Rejected by lecturer
);

CREATE TYPE session_status AS ENUM (
    'NOT_STARTED',
    'IN_PROGRESS',
    'COMPLETED',
    'CANCELLED'
);

CREATE TYPE turn_type AS ENUM (
    'MAIN_QUESTION',      -- Main question retrieved from the bank
    'ADAPTIVE_FOLLOW_UP' -- Dynamic AI follow-up based on student response
);

CREATE TYPE evaluation_status AS ENUM (
    'PENDING_AI',       -- Awaiting AI transcript evaluation
    'AWAITING_REVIEW',  -- AI grading completed, awaiting lecturer sign-off
    'CONFIRMED',        -- Lecturer confirmed final scores
    'DISPUTED'          -- Student disputed the evaluation
);

-- ============================================================================
-- MODULE 0: IDENTITY / RBAC & COURSE MODULE
-- ============================================================================

CREATE TABLE roles (
    role_id SMALLINT PRIMARY KEY,
    role_name VARCHAR(20) UNIQUE NOT NULL,
    role_description TEXT
);

COMMENT ON TABLE roles IS 'Table storing predefined static system roles (Strictly: ADMIN, LECTURER, STUDENT)';

-- Seed fixed system roles
INSERT INTO roles (role_id, role_name, role_description) VALUES
(1, 'ADMIN', 'System Administrator with full management access'),
(2, 'LECTURER', 'Course instructor managing materials, banks, and grading'),
(3, 'STUDENT', 'Candidate participating in viva interview sessions');

CREATE TABLE users (
    user_id UUID PRIMARY KEY,
    role_id SMALLINT NOT NULL REFERENCES roles(role_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_users_role_id ON users(role_id);
CREATE INDEX idx_users_email ON users(email);

CREATE TABLE courses (
    course_id UUID PRIMARY KEY,
    course_code VARCHAR(20) UNIQUE NOT NULL,
    course_name VARCHAR(150) NOT NULL,
    course_description TEXT,
    created_by UUID NOT NULL REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_courses_created_by ON courses(created_by);

-- ============================================================================
-- MODULE 1: QUESTION BANK & KNOWLEDGE MODULE
-- ============================================================================

CREATE TABLE documents (
    document_id UUID PRIMARY KEY,
    course_id UUID NOT NULL REFERENCES courses(course_id) ON UPDATE CASCADE ON DELETE CASCADE,
    file_name VARCHAR(255) NOT NULL,
    file_url VARCHAR(500) NOT NULL,
    is_indexed BOOLEAN DEFAULT FALSE NOT NULL,
    uploaded_by UUID NOT NULL REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_documents_course_id ON documents(course_id);
CREATE INDEX idx_documents_uploaded_by ON documents(uploaded_by);

CREATE TABLE questions (
    question_id UUID PRIMARY KEY,
    course_id UUID NOT NULL REFERENCES courses(course_id) ON UPDATE CASCADE ON DELETE CASCADE,
    content TEXT NOT NULL,
    sample_answer TEXT,
    bloom_level bloom_level NOT NULL,
    status question_status DEFAULT 'DRAFT_AI' NOT NULL,
    source_document_id UUID NOT NULL REFERENCES documents(document_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    created_by UUID NOT NULL REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_questions_course_id ON questions(course_id);
CREATE INDEX idx_questions_source_doc ON questions(source_document_id);
CREATE INDEX idx_questions_created_by ON questions(created_by);

CREATE TABLE rubric_criteria (
    criteria_id UUID PRIMARY KEY,
    question_id UUID NOT NULL REFERENCES questions(question_id) ON UPDATE CASCADE ON DELETE CASCADE,
    criteria_name VARCHAR(150) NOT NULL,
    criteria_description TEXT,
    max_score NUMERIC(4, 2) NOT NULL,
    weight NUMERIC(3, 2) DEFAULT 1.00 NOT NULL,
    CONSTRAINT chk_criteria_scores CHECK (max_score >= 0 AND weight >= 0)
);

CREATE INDEX idx_rubric_criteria_question ON rubric_criteria(question_id);

-- ============================================================================
-- MODULE 2: VIVA INTERVIEW SESSION MODULE
-- ============================================================================

CREATE TABLE exam_sessions (
    session_id UUID PRIMARY KEY,
    course_id UUID NOT NULL REFERENCES courses(course_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    student_id UUID NOT NULL REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    examiner_id UUID NOT NULL REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    start_time TIMESTAMP WITHOUT TIME ZONE,
    end_time TIMESTAMP WITHOUT TIME ZONE,
    session_status session_status DEFAULT 'NOT_STARTED' NOT NULL,
    full_audio_record_url VARCHAR(500),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_exam_sessions_time CHECK (end_time IS NULL OR start_time IS NULL OR end_time >= start_time)
);

CREATE INDEX idx_exam_sessions_course ON exam_sessions(course_id);
CREATE INDEX idx_exam_sessions_student ON exam_sessions(student_id);
CREATE INDEX idx_exam_sessions_examiner ON exam_sessions(examiner_id);

CREATE TABLE exam_turns (
    turn_id UUID PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES exam_sessions(session_id) ON UPDATE CASCADE ON DELETE CASCADE,
    parent_turn_id UUID REFERENCES exam_turns(turn_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    question_id UUID REFERENCES questions(question_id) ON UPDATE CASCADE ON DELETE SET NULL,
    turn_order INT NOT NULL,
    turn_type turn_type DEFAULT 'MAIN_QUESTION' NOT NULL,
    question_text TEXT NOT NULL,
    student_transcript TEXT,
    turn_audio_url VARCHAR(500),
    response_duration_sec INT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_session_turn_order UNIQUE (session_id, turn_order)
);

CREATE INDEX idx_exam_turns_session ON exam_turns(session_id);
CREATE INDEX idx_exam_turns_parent ON exam_turns(parent_turn_id);
CREATE INDEX idx_exam_turns_question ON exam_turns(question_id);

-- ============================================================================
-- MODULE 3: ASSESSMENT & HUMAN-IN-THE-LOOP MODULE
-- ============================================================================

CREATE TABLE grade_evaluations (
    evaluation_id UUID PRIMARY KEY,
    session_id UUID UNIQUE NOT NULL REFERENCES exam_sessions(session_id) ON UPDATE CASCADE ON DELETE CASCADE,
    lecturer_id UUID NOT NULL REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    ai_total_score NUMERIC(5, 2),
    final_total_score NUMERIC(5, 2),
    ai_general_feedback TEXT,
    lecturer_comment TEXT,
    evaluation_status evaluation_status DEFAULT 'PENDING_AI' NOT NULL,
    confirmed_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_grade_evaluations_lecturer ON grade_evaluations(lecturer_id);

CREATE TABLE turn_evaluation_details (
    detail_id UUID PRIMARY KEY,
    evaluation_id UUID NOT NULL REFERENCES grade_evaluations(evaluation_id) ON UPDATE CASCADE ON DELETE CASCADE,
    turn_id UUID NOT NULL REFERENCES exam_turns(turn_id) ON UPDATE CASCADE ON DELETE CASCADE,
    criteria_id UUID NOT NULL REFERENCES rubric_criteria(criteria_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    ai_score NUMERIC(4, 2),
    ai_justification TEXT,
    lecturer_score NUMERIC(4, 2)
);

CREATE INDEX idx_turn_eval_evaluation ON turn_evaluation_details(evaluation_id);
CREATE INDEX idx_turn_eval_turn ON turn_evaluation_details(turn_id);
CREATE INDEX idx_turn_eval_criteria ON turn_evaluation_details(criteria_id);